version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catering-backend
    ports:
      - "8000:8000"
    volumes:
      - ./ml_models:/app/ml_models
    environment:
      - ML_MODELS_PATH=ml_models
      - DEBUG=false
    restart: unless-stopped